### ISSUE TITLE
Only import incomplete tasks?

### ISSUE THREAD

**Issue by thomaschrstnsn** [tatsuo48/pull-asana-mytask#5]
It would be awesome to only include incomplete tasks when pulling from Asana.

In my workflow, I simply mark tasks as complete and they stay in the given section.
This means that I get a lot of completed tasks when pulling.

**Comment by tatsuo48** [comment]
Thank you for using!
Let's think about whether it is feasible.

**Comment by tatsuo48** [comment]
https://github.com/tatsuo48/pull-asana-mytask/releases/tag/v0.3.1
Released!
Please try using it.

**Comment by thomaschrstnsn** [comment]
Awesome, works perfectly!

**Comment by thomaschrstnsn** [comment]
Thanks for taking the time
